info:
    serviceLinks:
        api-doc: "${route.name}/docs/index.html"
    dependencies:
        skatteetaten: "skatteetaten"

spring:
    profiles:
        active: local
    datasource:
        # Change the maximum pool size if your application needs it.
        hikari.maximumPoolSize: 3
    sleuth:
        enabled: false

logging:
    level:
      ske.aurora: INFO
      no.skatteetaten: INFO
      org:
        springframework: WARN
        apache.catalina: WARN
        hibernate: WARN

---
spring:
  profiles: local
  datasource:
    url: ${refapp.datasource.url:jdbc:postgresql://localhost:5432/refapp}
    username: ${refapp.datasource.username:postgres}
    password: ${refapp.datasource.password:postgres}

management:
    server.port: 8081

logging:
    pattern:
      console: "%d [%-9.9thread] %-5level %logger %X - %msg %n%rEx{full}"

s3:
    buckets:
        referanse-java:
            serviceEndpoint: http://localhost:9000
            accessKey: minio
            secretKey: miniosecret
            bucketName: default
            objectPrefix: refapp
            bucketRegion: us-east-1
        referanse-java2:
            serviceEndpoint: http://localhost:9000
            accessKey: minio
            secretKey: miniosecret
            bucketName: default
            objectPrefix: refapp2
            bucketRegion: us-east-1
