info:
    serviceLinks:
        api-doc: "${route.name}/docs/index.html"
    dependencies:
        skatteetaten: "skatteetaten"

spring:
    profiles:
        active: local


logging:
    level:
      ske.aurora: INFO
      no.skatteetaten: INFO
      org:
        springframework: WARN
        apache.catalina: WARN
        hibernate: WARN

---
spring:
  profiles: local
  datasource:
    url: ${refapp.datasource.url:jdbc:oracle:thin:@host:port/path}
    username: ${refapp.datasource.username:username}
    password: ${refapp.datasource.password:password}


keepalive:
  host: "http://localhost:8080"
  wait: 100
  number: 10

management:
    server.port: 8081


logging:
    level:
        no.skatteetaten.aurora.openshift.reference.springboot: DEBUG
    pattern:

      console: "%d [%-9.9thread] %-5level %logger %X - %msg %n%rEx{full}"

